{% set name = "dadi" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c1ce82e50d5f2fc66f06853f67a8f05a36bb3ba54ce12586419c870776e5ff4

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --install-option="--cython" '

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - pip
    - cython
    - python
    - numpy
    - nlopt
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base
    - nlopt

test:
  imports:
    - dadi
    - dadi.DFE
    - dadi.Triallele
    - dadi.TwoLocus

about:
  home: https://bitbucket.org/gutenkunstlab/dadi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Fit population genetic models using diffusion approximations to the allele frequency spectrum
  doc_url: https://dadi.readthedocs.io/

extra:
  recipe-maintainers:
    - RyanGutenkunst
